import { Box } from "@chakra-ui/react"
import type { NextPage } from "next"
import Head from "next/head"
// import styles from "../styles/Home.module.css"

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h1>
        Hello
        <Box bg='brand.100'>Reddit</Box>
        clone sessions
      </h1>
    </div>
  )
}

export default Home
